#MiyoApp
FROM node:22-alpine AS miyoBuild
WORKDIR /usr/src/app

# Copy package.json and yarn.lock first for better caching
COPY --chown=node:node package.json yarn.lock ./

# Install dependencies
RUN yarn install --frozen-lockfile

# Copy the rest of the application
COPY --chown=node:node . .

# Build applications
RUN NODE_OPTIONS="--max-old-space-size=4096" yarn nx run portal-app:build:production

USER node

# PRODUCTION
FROM nginx:1.27.5-bookworm
COPY nginx-web.conf /etc/nginx/conf.d/default.conf

# Copy built applications
COPY --from=miyoBuild /usr/src/app/dist/apps/portal-app /usr/share/nginx/html
