###################
# BUILD FOR PRODUCTION
###################
FROM node:22-alpine As build
WORKDIR /usr/src/app
RUN apk add g++ make python3
COPY --chown=node:node . .
COPY .env /usr/src/app/.env
RUN yarn global add @nestjs/cli@10.4.5 husky
RUN yarn install --legacy-peer-deps
RUN yarn nx run portal-api:build:production
USER node

###################
# PRODUCTION
###################
FROM node:22-alpine As production
WORKDIR /usr/src/app
COPY --chown=node --from=build /usr/src/app/dist/apps/portal-api/package.json ./
COPY yarn.lock ./
COPY .env ./
RUN yarn install --legacy-peer-deps --only=production
RUN yarn add pg
COPY --chown=node:node --from=build /usr/src/app/dist/apps ./
CMD [ "node", "./portal-api/main.js" ]
