# name: Docker Image CI
# on:
#   push:
#     branches: ['develop_deploy']
#     # tags:
#     #   - 'dev-v*'
# env:
#   NAME: 'dev'
# jobs:
#   Flyway:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Cache Node.js modules
#         id: smart_cache
#         uses: actions/cache@v3
#         with:
#           path: ~/.cache/yarn
#           key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: ${{ runner.os }}-yarn-

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ap-south-1
#       - name: Login to Amazon ECR Private
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1
#       - name: Build, tag, and push flyway docker image to Amazon ECR
#         env:
#           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           REPOSITORY1: smart-dev/flywaydb
#           IMAGE_TAG: ${{ github.sha }}
#         run: |
#           docker build -t $REGISTRY/$REPOSITORY1:$IMAGE_TAG --file Dockerfile.flyway .
#           docker push $REGISTRY/$REPOSITORY1:$IMAGE_TAG
#       - name: Clean up Docker images
#         run: docker system prune -af                    

#   PortalApi:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Cache Node.js modules
#         id: smart_cache
#         uses: actions/cache@v3
#         with:
#           path: ~/.cache/yarn
#           key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: ${{ runner.os }}-yarn-

#       # - name: Install NestJS CLI to run Lint and Unit Tests
#       #   run: yarn add global @nestjs/cli@10.4.5

#       # - name: Install dependencies to run Lint and Unit Tests
#       #   run: yarn install --legacy-peer-deps     

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ap-south-1
#       - name: Login to Amazon ECR Private
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Build, tag, and push Portal API docker image to Amazon ECR
#         env:
#           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           REPOSITORY2: smart-dev/portal-api
#           IMAGE_TAG: ${{ github.sha }}
#           S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
#         run: |
#               # echo "is Develp branch"
#               echo ${{ github.ref }}              
#               echo $NAME
#               aws s3 cp s3://$S3_BUCKET_NAME/smart/dev-api.env ./
#               mv dev-api.env .env  
#               docker build -t $REGISTRY/$REPOSITORY2:$IMAGE_TAG --file Dockerfile.PortalAPI .
#               docker push $REGISTRY/$REPOSITORY2:$IMAGE_TAG
#       - name: Clean up Docker images
#         run: docker system prune -af                    
                                  
#   webApps:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Cache Node.js modules
#         id: smart_cache
#         uses: actions/cache@v3
#         with:
#           path: ~/.cache/yarn
#           key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: ${{ runner.os }}-yarn-
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ap-south-1
#       - name: Login to Amazon ECR Private
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1
#       - name: Build, tag, and push Portal APP docker image to Amazon ECR
#         env:
#           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           REPOSITORY3: smart-dev/web-app
#           IMAGE_TAG: ${{ github.sha }}
#           S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
#         run: |
#               # echo "is Develp branch"
#               echo ${{ github.ref }}              
#               echo $NAME
#               aws s3 cp s3://$S3_BUCKET_NAME/smart/dev-web.env ./
#               mv dev-web.env .env        
#               docker build -t $REGISTRY/$REPOSITORY3:$IMAGE_TAG --file Dockerfile.Web .
#               docker push $REGISTRY/$REPOSITORY3:$IMAGE_TAG
#       - name: Clean up Docker images
#         run: docker system prune -af                    

#   EksDeploy:
#     runs-on: ubuntu-latest
#     needs:
#       - Flyway
#       - PortalApi
#       - webApps 
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           path: main
#       - name: checkout config repo
#         uses: actions/checkout@v3
#         with:
#           repository: SmartsChoiceEdu/smart-eks-blueprints-helm
#           token: ${{  secrets.CONFIG_PAT}}
#           path: master
#           ref: master
#       - name: update eks-config repos
#         env:
#           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           REPOSITORY1: flywaydb
#           REPOSITORY2: portal-api
#           REPOSITORY3: web-app 
#           IMAGE_TAG: ${{ github.sha }}
#         run: |
#           cd master
#           sed  -i "s/$REPOSITORY1:.*/$REPOSITORY1:$IMAGE_TAG/" projects/dev/templates/flyway-job.yaml
#           sed  -i "s/$REPOSITORY2:.*/$REPOSITORY2:$IMAGE_TAG/" projects/dev/templates/portal-api-deployments.yaml
#           sed  -i "s/$REPOSITORY3:.*/$REPOSITORY3:$IMAGE_TAG/" projects/dev/templates/web-app-deployments.yaml                                                                                                                  
#           git config user.name system
#           git status
#           git add .
#           git commit -m "updated config during ${{ github.sha }} update"
#           git push origin master
